FROM openjdk:12

ADD testable-spring-boot2x-webapp.jar /usr/local/testable-spring-boot2x-webapp/

WORKDIR /usr/local/testable-spring-boot2x-webapp/

CMD ["java", "-jar", "testable-spring-boot2x-webapp.jar"]