name: build VAuthenticator Management UI

on:
  push: { }

jobs:
  build-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: |
          cd management-ui
          ./production-build.sh

      - name: docker push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

          if [[ ${GITHUB_REF##*/} == 'main' ]]
          then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${GITHUB_REF##*/}"
          fi
          cd management-ui

          echo "$DOCKER_TAG"
          docker build -t mrflick72/vauthenticator-management-ui-k8s:$DOCKER_TAG -f Dockerfile .
          docker push mrflick72/vauthenticator-management-ui-k8s:$DOCKER_TAG
